[package]
name = "piston-emscripten-text"
version = "0.1.0"
authors = ["Remi Rampin <remirampin@gmail.com>"]
license = "BSD-3-Clause"
description = "Example Piston app on Emscripten, text rendering bug"

[[bin]]
name = "piston-emscripten-text"
path = "src/main.rs"

[dependencies]
# Abstract graphics
piston = "0.35"
piston2d-graphics = "0.23"

# Concrete graphics
piston2d-opengl_graphics = "0.49"
pistoncore-sdl2_window = "0.46"
sdl2 = "0.30"

[target.'cfg(target_os = "emscripten")'.dependencies]
emscripten-sys = "0.3"

[features]
default = ["sdl2/use_mac_framework"]
use_sdl2_mac_framework = ["sdl2/use_mac_framework"]
